### PR TITLE
Add kmp to the build string to indicate intel ABI

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
Can you add any links and an explanation of what this is for?

**Comment by isuruf** [comment]
LLVM openmp uses the Intel ABI symbols `kmp_*` and also has GNU ABI symbols `gomp_*`. I want to add `intel-openmp` package too and be able to say use either `llvm-openmp` or `intel-openmp`. A build string with `kmp_` makes it possible to say that.

**Comment by beckermr** [comment]
So the possible things will be:

 - intel build string will be matched with `*kmp`
 - only llvm is `*llvm`
 - either intel or llvm is `*kmp*`
 - gnu is `*gnu`

Are we disfavoring the same logic applied to llvm and gnu? 

Should we add `gnu` too here so we can add a case that is 

 - gnu or llvm is `*gnu*`

I might not be following your logic though.

**Comment by isuruf** [comment]
> Should we add gnu too here so we can add a case that is

    gnu or llvm is *gnu*

`intel-openmp` and hence all three have the `GOMP_*` symbols. So, there's no need to select gnu or llvm only

**Comment by beckermr** [comment]
I see your point. I mostly want to make sure the effective API on the mutexes is easy to interp. Enabling 
 
  - `*<name>` to always mean only `<name>`
  - `*<name>*` to always mean anything compatible w/ `<name>` 

is symmetric across all versions.

As it stands now, anything compatible with `gnu` is just a plain `*` which is different from say `kmp`.

**Comment by isuruf** [comment]
> is symmetric across all versions and very much unsurprising.

Agreed

> As it stands now, anything compatible with gnu is just a plain * which is different from say kmp.

Yes, since it's all implementations are compatible with gnu, just `conda install _openmp_mutex` is enough without any build string. IMHO, I don't think it's necessary to add `gomp` to all of the build strings.

**Comment by beckermr** [comment]
OK. I don't feel too strongly on this one so happy to defer to you. Thanks for the discussion.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Review by beckermr — APPROVED** [review]

**Pull request merged**
